print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Kadda/Trump-n-Run/trump_n_run/Assets/Tumbleweed/tumbleweed.mb"`)
{		
	file -o "/Users/Kadda/Trump-n-Run/trump_n_run/Assets/Tumbleweed/tumbleweed.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Kadda/Trump-n-Run/trump_n_run/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/Kadda/Trump-n-Run/trump_n_run/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/Kadda/Trump-n-Run/trump_n_run/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
